project:
  name: cfn-ps-connect-integration-perficient-msdynamics
  owner: quickstart@amazon.com
  package_lambda: false
  regions:
  - us-east-1
tests:
  defaults:
    parameters: {}
    regions:
    - us-east-1
    template: templates/perficient-msdynamics.template.yaml
